version: "3.9"
services:
  app:
    build: 
      context: .
      dockerfile: ./infra/php/Dockerfile

  web:
    build: 
      context: .
      dockerfile: ./infra/nginx/Dockerfile
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/html

  db:
    build: ./infra/mysql
    volumes:
      - db-store:/var/lib/mysql

volumes:
  db-store:
